import { Property } from './types';

export const PROPERTIES: Property[] = [
    {
        id: "sea-breeze",
        title: "Sea Breeze Studio",
        location: "An Thuong Area",
        distance: "5 min walk to beach",
        rating: 4.92,
        price: 450,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCUZLyGRxlk_AUNQZmhnS1e8NF7iv_i7Ej7MnsJsGWX0waUpU6Qw6Jf8OJ5-uLWmt3C6X3CL0vOFDjPL5bA35nQ0zm0h5YqGtaOulZpTuSq51lmeSmHKgdbOFL65PmPv5hqauT-yHGT40xVqD-dR5vnvS3qOW-I7d596jZwTr6rVidAL9XR0Vh-TLCA7X01e2n8OCdIrryQ_IReDUvB4KMPERhm7vPLhLewUYj-3bPnxpohhrGq9Kw-GNCXk3IAujmqh2d_EhbDl-U",
        wifi: "85 Mbps",
        amenities: ["Desk", "Laundry"],
        reviews: 24,
        desc: "An Thuong Area • 5 min walk to beach",
        type: "Studio",
        latitude: 16.052,
        longitude: 108.243
    },
    {
        id: "green-oasis",
        title: "Green Oasis 1BR",
        location: "Son Tra",
        distance: "Quiet neighborhood",
        rating: 4.85,
        price: 600,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA5LzmMvntPhvYzstdMivFSM2kCG8p_0ZL76sGGlBKiig07RWqiZCKbJHIc3oITEZ-38lhJMLDCAFpJG6zPBoEEREXDx-IKepkvFL8xrPPAv2GPFQOLq3NcbzCaEvlARGEpb46IcqwUtGVlBeNiZTC8HlyVeDuFwfV0_nkv4mPUr4yYu850YPZUQWXBwNK3D6VvMffOncIIjU6vJZXG3bMTqsbl071090UNF7PqeDL65Z6BChqbkJtbFV7rKed7bVhrlgZeZHmyZzA",
        wifi: "120 Mbps",
        amenities: ["Monitor", "Pool"],
        reviews: 18,
        desc: "Son Tra • Quiet neighborhood",
        type: "1BR",
        latitude: 16.080,
        longitude: 108.240
    },
    {
        id: "skyline-loft",
        title: "Skyline Loft",
        location: "Hai Chau",
        distance: "City center",
        rating: 5.0,
        price: 850,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDlSx2Loe7EWNYAkNdQiTRqcxLouZg_Oi1VeKiv4yvPa_e8Hyx4qdENWv8VSthnDKp0zNHzQkjAK7J8vERuJWb9_GXBSYL7NdSK16jP-7dK2SvwpRguKDH3EEhd1Z0P_xGyeV4iAX4rbqBgIJPM8uzi0YNWZ7DKG5R8dkuew_vYCO_sEkjYarziC1gDraSQ66noPXqpeudkygrRnun6uT-Mfft9up7QFtjh6UliyBimeZaUp7ilOf_y4G04N4XmJMB14znU9rwnTtk",
        wifi: "200 Mbps",
        amenities: ["Ergo Chair", "Gym"],
        reviews: 42,
        desc: "Hai Chau • City center",
        type: "Loft",
        latitude: 16.065,
        longitude: 108.220
    },
    {
        id: "modern-studio",
        title: "Modern Studio near My Khe Beach",
        location: "My An, Da Nang",
        rating: 4.9,
        price: 650,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCdJf84Yj0AGyHNGR7By43h56eDseylPtXmATklpaDTfFmn_4adpYRoBlYNPbck0FgD5JZ-k9f5R7yuq8lOyTL_cDpk0vbKj7OhMUduai_EC3JvCHNFCvR0_v6QZrOMq0iYOTbj2TBuAP7zAkXGZnS3JXvI45q3dsWavvAtT-4q6pbAOUDaZR3IRjH-LICPMb3D9Nvcn2ya4_lzx7gxAXTnS1IxYjRsAkINIM56GMnoWnJnDRULHV9aERZsuBDYZs3W-DiAsBKCT_U",
        wifi: "85 Mbps",
        nomadScore: 92,
        amenities: ["Ergo"],
        desc: "Bills Incl.",
        type: "Studio",
        latitude: 16.050,
        longitude: 108.245
    },
    {
        id: "riverfront-luxury",
        title: "Riverfront Luxury Suite",
        location: "Hai Chau, Da Nang",
        rating: 4.95,
        price: 950,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuALB8yjrOXUMGf7giPELDhp67mmqQdS_sqMjzygGt8FKnGSNp-G6zpioMGROoyOLBhHj4XVJj7twYnC5s4p38gc44bV544HT1cbOqalVzHh1sdXjmBp7SqrWaflxjgKux27jbfN7xSTXSOdy2fchzNofcEoAidEFO9WXfx1VuWy4JWa1zU20wun5QXj09VXaCZb9cJl0mhoSb3p4xYyMF5POBUZntpjzNLMrK-8SR1gKViIs5IHUfSXPNV3fatkqPAu1tCo9oDhWJY",
        wifi: "200 Mbps",
        nomadScore: 88,
        amenities: ["Stand"],
        desc: "Cleaning Incl.",
        type: "Suite",
        latitude: 16.070,
        longitude: 108.225
    },
    {
        id: "nomad-hub",
        title: "Nomad Hub Apartment",
        location: "Son Tra, Da Nang",
        rating: 4.8,
        price: 550,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDAy3JCfCl44GEFD6zU0ct1yhwkPj3kdQGUXKxYeWQpOwrhrf3c6sh1FVNIuopUPpREc2bR9Yz6Rzx47DIq7mK0Mq75UfiTMTecxYiH2UiwN-g4wa8gtU258IZ8j5VR8ehAVyEK_lQEvo1EXtJwKT60t3NtY29UY9qM9XaOq-pM4ZBBnlehUeX-6Co_thoRJjfx3wxZgjORqhkA4T6_fYsoOT-WIzUHGwtQSLAc245-If3aci7YbMLpULSTdssFro1Eu9-k7YHNJSo",
        wifi: "100 Mbps",
        nomadScore: 80,
        amenities: ["Large Table"],
        desc: "3 Month min",
        type: "1BR",
        latitude: 16.085,
        longitude: 108.242
    },
    {
        id: "ocean-view-2br",
        title: "Ocean View 2BR Condo",
        location: "My Khe, Da Nang",
        rating: 5.0,
        price: 1100,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB3dY3ZHCjZ0T0qdGBVz4xCmwoR2yuBk9SEs7ik-Eu96pY13Mau9-DQnl5L_rG5vSX2oUA_Yp1mgde1Qzaqzj67d36uWmD2WHjlAyDV4-fdwvIBTvLeXOExcQDP_sbT-KUt1TGRCqCN_NCRRI12UVa-6D8zfwUunqegUl5cFs_x0PmrYNcPvfImfelDUEy-3h6-2KISYOyw7mBzFbropKO5lphAm4hZdk_u91JpF5xzgB5BvQ-GPqCF0F00Re4Osyix8vvTkaxqIs0",
        wifi: "150 Mbps",
        nomadScore: 95,
        amenities: ["2x Mon"],
        desc: "Gym + Pool",
        type: "2BR",
        latitude: 16.060,
        longitude: 108.244
    }
];